{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.mending.core",
    "module": "paper-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "paper-api-1.0.0-SNAPSHOT.jar",
          "url": "paper-api-1.0.0-SNAPSHOT.jar",
          "size": 23227,
          "sha512": "a13cc9e03bfd16d77cf15bcece22857d1c23c8bd02f9122169f0b048910380302dae1630ee10cd26b0fe26853d0930e4f32c5775ef5a984ec39dd65564f7ace8",
          "sha256": "dd59f698ffa605046cd6942c11aed330962913ea60724f217e13866ae0a23858",
          "sha1": "f495b66eff0cecea6429971d89db20a980e4509e",
          "md5": "ce75b759ae385d6952de9c2bc93850f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paper-api-1.0.0-SNAPSHOT.jar",
          "url": "paper-api-1.0.0-SNAPSHOT.jar",
          "size": 23227,
          "sha512": "a13cc9e03bfd16d77cf15bcece22857d1c23c8bd02f9122169f0b048910380302dae1630ee10cd26b0fe26853d0930e4f32c5775ef5a984ec39dd65564f7ace8",
          "sha256": "dd59f698ffa605046cd6942c11aed330962913ea60724f217e13866ae0a23858",
          "sha1": "f495b66eff0cecea6429971d89db20a980e4509e",
          "md5": "ce75b759ae385d6952de9c2bc93850f8"
        }
      ]
    }
  ]
}
