{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.mending.core",
    "module": "paper-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "paper-api-1.0.0-SNAPSHOT.jar",
          "url": "paper-api-1.0.0-SNAPSHOT.jar",
          "size": 37282,
          "sha512": "65bc268a49b60ebfe12a4dcb41b991f2a6af81721cc5008b8cb3ddeb4829d170b7b249efbc1fa0b039cdd4e0db1471c8cf30e38ba98b0bd939f8d77662f71569",
          "sha256": "b1ae2e135e066a7527944490369258f4d186b47e4efcc0ef67cf3a007699ca53",
          "sha1": "28eb00896dbc8b895b63e94beb0df545eb5a49fe",
          "md5": "ed847b1d9c78136f3b18793cbd7d020b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paper-api-1.0.0-SNAPSHOT.jar",
          "url": "paper-api-1.0.0-SNAPSHOT.jar",
          "size": 37282,
          "sha512": "65bc268a49b60ebfe12a4dcb41b991f2a6af81721cc5008b8cb3ddeb4829d170b7b249efbc1fa0b039cdd4e0db1471c8cf30e38ba98b0bd939f8d77662f71569",
          "sha256": "b1ae2e135e066a7527944490369258f4d186b47e4efcc0ef67cf3a007699ca53",
          "sha1": "28eb00896dbc8b895b63e94beb0df545eb5a49fe",
          "md5": "ed847b1d9c78136f3b18793cbd7d020b"
        }
      ]
    }
  ]
}
